# 다차원 배열의 차원 수 

In [2]:
import numpy as np
A = np.array([[1,2],[2,3],[3,4]])
print(A)
print(" 차원 수 : np.ndim(A):", np.ndim(A))
print("A.shape : ", A.shape)

[[1 2]
 [2 3]
 [3 4]]
 차원 수 : np.ndim(A): 2
A.shape :  (3, 2)


In [3]:
B = np.array([[[1,1],[1,1],[1,1]],[[2,2],[2,2],[2,2]]])
print(B)
print(" 차원 수 : np.ndim(B):", np.ndim(B))
print("B.shape : ", B.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]]]
 차원 수 : np.ndim(B): 3
B.shape :  (2, 3, 2)


# 신경망 구현하기 (FORWARD 만)

In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [16]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

print("X.shape : ",X.shape)
print("W1.shape : ",W1.shape)
print("B1.shape : ",B1.shape)

A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)
print("A1.shape : ",A1.shape)
print("Z1.shape : ",Z1.shape)

print(" ##중요## : W1의 shape은 X(입력)의 갯수, A1(출력)의 갯수 ")
print(" ##중요## : B1(편향)의 shape은 출력의 shape (출력갯수) 가 동일 ")
print("\n ##중요## : 열이 갯수 ################################### ")

X.shape :  (2,)
W1.shape :  (2, 3)
B1.shape :  (3,)
A1.shape :  (3,)
Z1.shape :  (3,)
 ##중요## : W1의 shape은 X(입력)의 갯수, A1(출력)의 갯수 
 ##중요## : B1(편향)의 shape은 출력의 shape (출력갯수) 가 동일 

 ##중요## : 열이 갯수 ################################### 


In [17]:
print(Z1)

[0.57444252 0.66818777 0.75026011]


In [18]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

A2 = np.dot(Z1,W2) +B2
Z2 =sigmoid(A2)

print(Z2)

[0.62624937 0.7710107 ]


In [20]:
print(" ##중요## : 출력함수의 활성화 함수 구현 (출력층의 활성화 함수는 은닉층과 다름)")
def identity_func(x):
    return x

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3) + B3
Z3 = identity_func(A3)
print("최종 OUTPUT : ", Z3)

 ##중요## : 출력함수의 활성화 함수 구현 (출력층의 활성화 함수는 은닉층과 다름)
최종 OUTPUT :  [0.31682708 0.69627909]


# 신경망 FORWARD 구현을 모듈화

In [22]:
import numpy as np
def init_network():
    network = {}
    network['W1'] =  np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
    network['B1'] =  np.array([0.1,0.2,0.3])
    network['W2'] =  np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['B2'] =  np.array([0.1,0.2])    
    network['W3'] =  np.array([[0.1,0.3],[0.2,0.4]])
    network['B3'] =  np.array([0.1,0.2])
    
    return network
    
def func(x,w,b):
    return sigmoid(np.dot(x,w)+b)
    
def sigmoid(x):
    return 1/(1+np.exp(-x))

def identity_func(x):
    return x

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 = network['B1'], network['B2'], network['B3']
    
    y = identity_func( np.dot(func(func(x,W1,B1),W2,B2),W3) + B3 )
    return y

network = init_network()
x = np.array([1.0,0.5])

y = forward(network,x)
print(y)


    

[0.31682708 0.69627909]
