# 경사하강법 (gradient descent method : GDM)
기울기를 이용해 함수의 최솟값을 찾음

local optimum이나 안장점에 빠지지 않도록 주의!!

gradient_descent_method 함수에서는 적정한 lr와 반복변수를 설정해주면 0에 가까운 기울기를 return 함

In [1]:
def gradient_descent_method(f, init_x, lr=0.01, step_num=100) :
    x = init_x 
    
    for i in range(step_num) :
        grad = numerical_gradient(f,x)
        x-= lr * grad
        
    return x

# 기울기 : 모든 변수의 편미분을 벡터로 정리한 것을 기울기라고 함

In [6]:
def numerical_gradient(f,x) :
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        #f(x+h)계산
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        #f(x-h)계산
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad

### 수치미분 테스트

In [14]:
import numpy as np
def function_2(x) :
    return x[0]**2 + x[1]**2
    # return np.sum(x**2)
    
numerical_gradient(function_2, np.array([-3.0, 4.0]))

array([-6.,  8.])

# 경사하강법으로 function_2의 최솟값을 구한다.

In [16]:
init_x = np.array([-3.0, 4.0])
# 0에 가까운 기울기 return
gradient_descent_method(function_2, init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

 ### 학습률 너무 큰 경우 (0으로 안감)

In [18]:
init_x = np.array([-3.0, 4.0])
# 0에 가까운 기울기 return
gradient_descent_method(function_2, init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

### 학습률 너무 작은 경우 (0으로 안감)

In [19]:
init_x = np.array([-3.0, 4.0])
# 0에 가까운 기울기 return
gradient_descent_method(function_2, init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

### 적정한 학습률 설정 필요