# 신경망에서 기울기
# ★★★★ LOSS 함수 (손실함수) 에 대한 W 의 편미분, (x,t(정답)) 은 주어짐

### 실제로 기울기 구하는 코드 구현 

In [17]:
import sys, os
sys.path.append(os.pardir)

import numpy as np 
# from common.functions import softmax, cross_entropy_error
# from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 정규분포로 초기화
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self,x,t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        return loss

In [52]:
def cross_entropy_error(y,t) :

    if y.ndim == 1 :
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size


def softmax(a) :
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 값 복원
        it.iternext()   
        
    return grad


# simpleNet 실험

In [57]:
net = simpleNet()
print(net.W)

print(np.shape(net.W))

[[ 0.95794607  1.00913711 -1.25107913]
 [-2.04488536  0.18851768  0.5303227 ]]
(2, 3)


In [25]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-1.21383086 -0.96455715 -0.11134789]


In [26]:
np.argmax(p) # 최댓값의 인덱스

2

In [37]:
t = np.array([0,0,1])
net.loss(x,t)

print(net.predict(x))
print(net.loss(x,t))

[-1.21383086 -0.96455715 -0.11134789]
0.5642284108074607


In [65]:
# Loss 함수에 대한 편미분 !!!!!!!!!!!!!!!

def f(W):
    return net.loss(x,t)

dW = numerical_gradient(f, net.W)
print(dW)
# dW2 = numerical_gradient(net.loss, net.W)
# print(dW2)

[[ 0.05266529  0.40529447 -0.45795975]
 [ 0.07899793  0.6079417  -0.68693963]]


In [64]:
f = lambda w: net.loss(x,t)
dW2 = numerical_gradient(f, net.W)
print(dW2)

[[ 0.05266529  0.40529447 -0.45795975]
 [ 0.07899793  0.6079417  -0.68693963]]
